#!/usr/bin/env python3
import logging
import os

import mlflow
from mlflow_log import MODEL_INPUT, MODEL_NAME

if __name__ == "__main__":
    model_stage_format = "models:/{task}/{stage}"
    model_version_format = "models:/{task}/{model_version}"

    usr = os.environ.get("MLFLOW_TRACKING_USERNAME")
    pwd = os.environ.get("MLFLOW_TRACKING_PASSWORD")

    mlflow.set_tracking_uri(f"https://{usr}:{pwd}@ml.madi.bio")
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s | %(message)s"
    )

    # Fetch model from registry
    logged_model = model_stage_format.format(task=MODEL_NAME, stage="staging")
    model = mlflow.pyfunc.load_model(logged_model)
    model_output = model.predict(MODEL_INPUT)

    print(model_output)
